### Полезные команды

(находясь в командном режиме)

- `a` - добавить пустую ячейку сверху

- `b` - добавить пустую ячейку снизу
- `c` - скопировать текущую ячейку
- `v` - вставить скопированную ячейку
- `d` - удалить текущую ячейку
- `x` - вырезать (удалить и скопировать) текущую ячейку
- `m` - изменить тип выбранной ячейки на "разметка" 
- `y` - изменить тип выбранной ячейки на "код" 
- `z` - отменить последнее действие


- `Enter` - начать редактировать выбранную ячейку

(будучи в режим редактирования ячейки)
- `esc` - вернуться в командный режим

(будучи в любом режиме)

- `Ctrl + Enter` - запустить выбранную ячейку
- `Shift + Enter` - запустить выбранную ячейку и выбрать следующую

In [2]:
import numpy as np

### Генератор верхнетреугольной единичной матрицы:

In [51]:
size = 5
result = np.zeros(shape=(size, size), dtype=int)
for i in range(-1-size,size,2):
    result = result + np.eye(N=size, M=size, k=i, dtype=int)
print(result)

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [52]:
size = 5
result = np.zeros(shape=(size, size), dtype=int)
for i in range(-size,size,2):
    result = result + np.eye(N=size, M=size, k=i, dtype=int)
print(result)

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


In [56]:
size = 5
result = np.zeros(shape=(size, size), dtype=int)
for i in range(0,size):
    result = result + np.eye(N=size, M=size, k=i, dtype=int)
print(result)

[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]


### Задания

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [79]:
n = np.random.randint(1, 100, size=10)
print(n)

reverse = n[::-1]
print(reverse)

[ 2 40 11 29 42 86 11 89 14 69]
[69 14 89 11 86 42 29 11 40  2]


In [80]:
print(max(n))

89


In [86]:
mask = n % 2 == 1
n[mask] = -1

print(n)

[ 2 40 -1 -1 42 86 -1 -1 14 -1]


In [90]:
size = 5
n = np.arange(1,2*size,step=2)

print(np.flip(n))

[9 7 5 3 1]


In [28]:
arr = np.array([-9.99, 1.32, 2, 3, 4])
number = 1.33
arr_upd = np.abs(arr - 1.33)
print(arr[np.argmin(arr_upd)])
print(arr[np.argmax(arr_upd)])


1.32
-9.99


In [31]:
koefs = np.array([1, 2, 0, 1, -2])
number = 10

print(np.polyint(koefs))  # первообразная
print(np.polyder(koefs))  # производная

print(np.polyval(np.polyder(koefs), number))  # производная в точке

[ 0.2  0.5  0.   0.5 -2.   0. ]
[4 6 0 1]
4601
